
image: node:20

stages:
  - build
  - deploy
  - publish

variables:
  GITLAB_PACKAGE_REGISTRY: "registry.gitlab.com"
  GITLAB_PROJECT_PATH: "backlogic/UI/service-builder-vscode"  # Replace with your actual GitLab project path
  VSCE_PERSONAL_ACCESS_TOKEN: "your_vsce_personal_access_token"

.pipeline_rules:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  extends:
    - .pipeline_rules
  stage: build
  before_script:
    - apt-get update -qy
    # - apt-get install -y nodejs npm jq
    - apt-get install -y jq
    - npm install -g @vscode/vsce
    - npm install -g typescript
    - npm i --save-dev @types/node
    - npm i --save-dev @types/mocha
    - export VSCE_EXTENSION_NAME=$(cat package.json | jq -r .name)
    - export VSCE_EXTENSION_VERSION=$(cat package.json | jq -r .version)
    - export VSCE_PACKAGE_NAME=$VSCE_EXTENSION_NAME-v$VSCE_EXTENSION_VERSION.vsix
    - echo "VSCE_PACKAGE_NAME=$VSCE_PACKAGE_NAME"
    - tsc
  script:
    - npm install
    - vsce package -o ./$VSCE_PACKAGE_NAME

deploy to gitlab:
  stage: deploy
  before_script:
    - echo "VSCE_PACKAGE_NAME=$VSCE_PACKAGE_NAME"
  script:
    - mkdir deploy
    - cp ./$VSCE_PACKAGE_NAME deploy/
    - echo "@backlogic:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  artifacts:
    paths:
      - deploy/

publish:
  stage: publish
  script:
    - npm install
    - vsce publish -p $VSCE_PERSONAL_ACCESS_TOKEN
  only:
    - master
  when: manual
